### ISSUE TITLE
Documentation for level 1 BLAS function

### ISSUE THREAD

**Issue by VanioBegic** [oezgurmakkurt/blasoxide#1]
Hello, I was looking at this crate and found it especially inspiring since I had many troubles with BLAS bindings which are available for rust.

Idea of issue is that basically someone should start working on documentation during development ( I am going to make an effort most certainly ) .

As issue says, doucmenting atleast level 1 functions would be nice first issue

Update:
I recommend this be labeled as good first issue, and needed:documentation

**Comment by oezgurmakkurt** [comment]
Hi, I'm glad you are interested. Thats one of the reasons why I started this project, I don't like building c code with rust code since building rust code is so easy with cargo but c is always complicated.

Documentation would be great especially since some function signatures (like srotg) might be different from reference BLAS.

**Comment by oezgurmakkurt** [comment]
I am closing this since I want this library to be used by [blood](https://github.com/oezgurmakkurt/blood) which will handle storage and provide safe interfaces to all BLAS functions. Everything can be documented there.
